# .github/workflows/release.yaml

on:
  push:
    tags:
      - 'v*'

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin, solaris, openbsd, netbsd, freebsd, dragonfly]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "386"
            goos: dragonfly
          - goarch: "386"
            goos: solaris
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: dragonfly
          - goarch: arm
            goos: solaris
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: dragonfly
          - goarch: arm64
            goos: solaris

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: TRUE

    - name: Upload assets
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.19"
        project_path: "./api/cmd/"
        binary_name: "api"
        asset_name: "${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}"
        md5sum: FALSE
